### ISSUE TITLE
客户端报错

### ISSUE THREAD

**Issue by randoms** [randoms/SharpLink#7]
```
System.AggregateException: One or more errors occurred. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SharpTox.Core.Tox'.
   at SharpTox.Core.Tox.ThrowIfDisposed() in E:\workspace\SharpLink\SharpTox\SharpTox\Core\Tox.cs:line 2151
   at SharpTox.Core.Tox.get_IsConnected() in E:\workspace\SharpLink\SharpTox\SharpTox\Core\Tox.cs:line 55
   at Skynet.Base.Skynet.sendMsg(ToxId toxid, Byte[] msg) in E:\workspace\SharpLink\Skynet\Base\Skynet.cs:line 316
   at Skynet.Base.Skynet.sendRequest(ToxId toxid, ToxRequest req, Boolean& status) in E:\workspace\SharpLink\Skynet\Base\Skynet.cs:line 443
   at SharpLink.LinkClient.<HandShake>d__11.MoveNext() in E:\workspace\SharpLink\SharpLink\LinkClient.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SharpLink.LinkClient.Connect(Skynet mSkynet, String targetToxId, IPAddress ip, Int32 port, Action`1 msgHandler, Action closeHandler, Action`1 errorHander) in E:\workspace\SharpLink\SharpLink\LinkClient.cs:line 98
   at SharpLink.Program.<>c__DisplayClass0_1.<Main>b__1() in E:\workspace\SharpLink\SharpLink\Program.cs:line 136
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SharpTox.Core.Tox'.
   at SharpTox.Core.Tox.ThrowIfDisposed() in E:\workspace\SharpLink\SharpTox\SharpTox\Core\Tox.cs:line 2151
   at SharpTox.Core.Tox.get_IsConnected() in E:\workspace\SharpLink\SharpTox\SharpTox\Core\Tox.cs:line 55
   at Skynet.Base.Skynet.sendMsg(ToxId toxid, Byte[] msg) in E:\workspace\SharpLink\Skynet\Base\Skynet.cs:line 316
   at Skynet.Base.Skynet.sendRequest(ToxId toxid, ToxRequest req, Boolean& status) in E:\workspace\SharpLink\Skynet\Base\Skynet.cs:line 443
   at SharpLink.LinkClient.<HandShake>d__11.MoveNext() in E:\workspace\SharpLink\SharpLink\LinkClient.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SharpLink.LinkClient.Connect(Skynet mSkynet, String targetToxId, IPAddress ip, Int32 port, Action`1 msgHandler, Action closeHandler, Action`1 errorHander) in E:\workspace\SharpLink\SharpLink\LinkClient.cs:line 98
   at SharpLink.Program.<>c__DisplayClass0_1.<Main>b__1() in E:\workspace\SharpLink\SharpLink\Program.cs:line 136
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
```

**Comment by randoms** [comment]
```
System.AggregateException: One or more errors occurred. ---> System.ObjectDisposedException: Safe handle has been closed
  at System.Runtime.InteropServices.SafeHandle.DangerousAddRef (System.Boolean& success) [0x00025] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0 
  at (wrapper managed-to-native) SharpTox.Core.ToxFunctions:SelfGetConnectionStatus (SharpTox.Core.ToxHandle)
  at SharpTox.Core.Tox.get_IsConnected () [0x00007] in <f9bb004d935d44b9abd96d8d6354af21>:0 
  at Skynet.Base.Skynet.sendMsg (SharpTox.Core.ToxId toxid, System.Byte[] msg) [0x00068] in <e193e2bea4174220b851be7b719cdd78>:0 
  at Skynet.Base.Skynet.sendRequest (SharpTox.Core.ToxId toxid, Skynet.Models.ToxRequest req, System.Boolean& status) [0x00166] in <e193e2bea4174220b851be7b719cdd78>:0 
  at SharpLink.LinkClient+<HandShake>c__async0.MoveNext () [0x000fc] in <e33687cda7a24ad5915a4db594b1d330>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0 
  at SharpLink.LinkClient.Connect (Skynet.Base.Skynet mSkynet, System.String targetToxId, System.Net.IPAddress ip, System.Int32 port, System.Action`1[T] msgHandler, System.Action closeHandler, System.Action`1[T] errorHander) [0x0002f] in <e33687cda7a24ad5915a4db594b1d330>:0 
  at SharpLink.Program+<Main>c__AnonStorey0+<Main>c__AnonStorey1.<>m__0 () [0x000a0] in <e33687cda7a24ad5915a4db594b1d330>:0 
  at System.Threading.Tasks.Task.InnerInvoke () [0x00012] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0 
  at System.Threading.Tasks.Task.Execute () [0x00016] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0 
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ObjectDisposedException: Safe handle has been closed
  at System.Runtime.InteropServices.SafeHandle.DangerousAddRef (System.Boolean& success) [0x00025] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0 
  at (wrapper managed-to-native) SharpTox.Core.ToxFunctions:SelfGetConnectionStatus (SharpTox.Core.ToxHandle)
  at SharpTox.Core.Tox.get_IsConnected () [0x00007] in <f9bb004d935d44b9abd96d8d6354af21>:0 
  at Skynet.Base.Skynet.sendMsg (SharpTox.Core.ToxId toxid, System.Byte[] msg) [0x00068] in <e193e2bea4174220b851be7b719cdd78>:0 
  at Skynet.Base.Skynet.sendRequest (SharpTox.Core.ToxId toxid, Skynet.Models.ToxRequest req, System.Boolean& status) [0x00166] in <e193e2bea4174220b851be7b719cdd78>:0 
  at SharpLink.LinkClient+<HandShake>c__async0.MoveNext () [0x000fc] in <e33687cda7a24ad5915a4db594b1d330>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0 
  at SharpLink.LinkClient.Connect (Skynet.Base.Skynet mSkynet, System.String targetToxId, System.Net.IPAddress ip, System.Int32 port, System.Action`1[T] msgHandler, System.Action closeHandler, System.Action`1[T] errorHander) [0x0002f] in <e33687cda7a24ad5915a4db594b1d330>:0 
  at SharpLink.Program+<Main>c__AnonStorey0+<Main>c__AnonStorey1.<>m__0 () [0x000a0] in <e33687cda7a24ad5915a4db594b1d330>:0 
  at System.Threading.Tasks.Task.InnerInvoke () [0x00012] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0 
  at System.Threading.Tasks.Task.Execute () [0x00016] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0 <---
```
